line_order:
    resource: "@LineOrderBundle/Controller/"
    type:     rest
    prefix:   /line

order:
    resource: "@OrderBundle/Controller/"
    type:     rest
    prefix:   /order

client:
    resource: "@ClientBundle/Controller/"
    type:     rest
    prefix:   /client

category:
    resource: "@CategoryBundle/Controller/"
    type:     rest
    prefix:   /category

article:
    resource: "@ArticleBundle/Controller/"
    type:     rest
    prefix:   /article
